Repository microsoft/vscode-black-formatter, pull requests merged in 2022-08, with the labels that each got.

#108 Update black formatter extension to latest extension template.
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/push-check.yml
  .vscode/launch.json
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  bundled/formatter/format_server.py
  bundled/formatter/runner.py
  bundled/tool/__init__.py
  bundled/tool/_debug_server.py
  bundled/tool/jsonrpc.py
  bundled/tool/runner.py
  bundled/tool/server.py
  bundled/tool/utils.py
  noxfile.py
  package-lock.json
  package.json
  package.nls.json
  requirements.txt
  src/common/constants.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
  src/setupNLS.ts
  src/test/python_tests/lsp_test_client/defaults.py
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_path_specialization.py
  src/test/test_argv_duplication.py
  webpack.config.js
Labels: debt

#110 Update version for release.
  package-lock.json
  package.json
Labels: no-changelog

#111 Update main to next pre-release.
  package-lock.json
  package.json
Labels: no-changelog

#113 Fix missing `typed_ast` when using python 3.7.
  bundled/tool/server.py
  noxfile.py
Labels: bug

#115 Add codereview chat
  .github/workflows/pr-chat.yml
Labels: no-changelog

#117 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt
