Repository microsoft/vscode-black-formatter, pull requests merged in 2022-05, with the labels that each got.

#33 Restarting should use the same python
  .github/workflows/pr-labels.yml
  src/common/formatLS.ts
Labels: bug, skip news

#39 Update Labels
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/issue-labels.yml
  .github/workflows/pr-labels.yml
Labels: debt, skip news

#51 Update packages
  .github/dependabot.yml
  bundled/formatter/format_server.py
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt, skip news

#64 Update packages
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt, skip news

#57 Corrected argv duplication bug
  bundled/formatter/format_server.py
  src/test/test_argv_duplication.py
Labels: bug, news
