Repository microsoft/vscode-black-formatter, pull requests merged in 2022-10, with the labels that each got.

#133 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#134 Update to use latest python environment APIs
  package-lock.json
  package.json
  src/common/python.ts
Labels: feature-request

#139 Update CHANGELOG.md
  CHANGELOG.md
Labels: no-changelog

#140 Handle file without workspace scenario.
  bundled/tool/server.py
  src/extension.ts
Labels: bug

#141 Fix for pydantic crash on Python 3.11
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  README.md
  noxfile.py
  requirements.txt
Labels: bug

#143 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog
