Repository microsoft/vscode-black-formatter, pull requests merged in 2023-05, with the labels that each got.

#227 Updating to node 16 along with all the dependencies
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#216 Ensure variable substitutions have right context
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  package.json
  src/common/settings.ts
Labels: feature-request

#228 Ensure black is always added as fallback
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
Labels: bug

#230 Fix labeling in dependa bot
  .github/dependabot.yml
Labels: no-changelog

#231 Set `customNPMRegistry` to empty
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: no-changelog

#232 Set `customNPMRegistry` to empty
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: no-changelog

#235 chore: sorted package.json for readability
  package.json
Labels: debt

#237 Fix propagating import strategy in multi-root case
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  noxfile.py
  package.json
  src/test/python_tests/test_formatting.py
Labels: bug
