Repository microsoft/vscode-black-formatter, pull requests merged in 2023-06, with the labels that each got.

#239 Ensure python is always requested using uri.
  src/common/server.ts
  src/common/settings.ts
  src/extension.ts
Labels: bug

#246 Package updates and minor fixes
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_server.py
  package-lock.json
  package.json
  requirements.txt
  src/common/settings.ts
  src/test/python_tests/requirements.txt
Labels: debt

#247 Update logging details in readme
  README.md
Labels: debt

#249 Engineering - update pre-release pipeline
  build/azure-pipeline.pre-release.yml
Labels: debt

#253 Engineering - re-enable Terrapin
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: debt

#254 Engineering - add TSAOptions
  build/azure-pipeline.stable.yml
Labels: no-changelog

#256 Mark virtual workspaces as unsupported in package.json
  package.json
Labels: bug

#259 Update packages and version for release
  noxfile.py
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#260 Update version to next pre-release
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
Labels: no-changelog
