Repository microsoft/vscode-black-formatter, pull requests merged in 2023-09, with the labels that each got.

#306 Makes version extraction more robust
  bundled/tool/lsp_server.py
Labels: bug

#308 Update packages
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#309 Add 'scripts' path to PATH
  bundled/tool/lsp_server.py
Labels: bug

#312 Fix mis-escaped string literal
  bundled/tool/lsp_server.py
Labels: bug

#324 Improve setting description for default interpreter setting
  README.md
Labels: debt, ghc-osd

#325 Capitalize instances of 'Python' in user-facing text
  package.nls.json
Labels: documentation, debt, ghc-osd

#322 Remove Python 3.7 from tests actions
  .github/workflows/pr-check.yml
Labels: debt, ghc-osd
