Repository microsoft/vscode-black-formatter, pull requests merged in 2023-10, with the labels that each got.

#336 Upgrade min version support to python 3.8
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  noxfile.py
  requirements.in
  requirements.txt
  runtime.txt
  src/common/python.ts
  src/extension.ts
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#329 Log when default formatter is not `ms-python.black-formatter`
  .vscode/settings.json
  src/common/constants.ts
  src/common/settings.ts
  src/extension.ts
Labels: bug

#326 Update dependency packages
  package-lock.json
  package.json
Labels: debt, ghc-osd

#337 Upgrade to node 18
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: debt

#339 Drop legacy settings support
  src/common/settings.ts
  src/extension.ts
Labels: debt

#342 Use narrow edits and range formatting warning
  bundled/tool/lsp_edit_utils.py
  bundled/tool/lsp_server.py
  requirements.txt
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_data/sample3/sample.py
  src/test/python_tests/test_data/sample3/sample.unformatted
  src/test/python_tests/test_edit_utils.py
  src/test/python_tests/test_formatting.py
Labels: bug

#358 Fix typo in README.md
  README.md
Labels: bug, documentation

#361 Update packages
  README.md
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog
