Repository microsoft/vscode-black-formatter, pull requests merged in 2023-11, with the labels that each got.

#362 Update version and packages for release
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  package-lock.json
  package.json
  package.nls.json
  src/common/python.ts
  src/common/server.ts
Labels: no-changelog

#363 Update main version to pre-release
  package-lock.json
  package.json
Labels: no-changelog

#366 Add env resolution and tests
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  .vscode/launch.json
  README.md
  package-lock.json
  package.json
  package.nls.json
  src/common/nullFormatter.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/status.ts
  src/common/utilities.ts
  src/common/vscodeapi.ts
  src/test/ts_tests/index.ts
  src/test/ts_tests/runTest.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
  src/test/ts_tests/tests/common/utilities.unit.test.ts
  tsconfig.json
Labels: bug

#368 Improve logging on syntax errors
  bundled/tool/lsp_server.py
Labels: bug

#373 Fix for `${fileDirname}` crash
  bundled/tool/lsp_server.py
  src/common/server.ts
Labels: bug

#367 Add more details to README and settings
  .vscode/launch.json
  README.md
  package.nls.json
Labels: documentation, debt

#388 Fix for LS client version collision with Pylance
  .vscode/settings.json
  package-lock.json
  package.json
Labels: bug
