Repository microsoft/vscode-black-formatter, pull requests merged in 2024-03, with the labels that each got.

#480 Engineering - add tsaoptions.json file
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  tsaoptions.json
Labels: no-changelog

#481 Revert "Engineering - add tsaoptions.json file"
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  tsaoptions.json
Labels: feature-request

#486 Engineering - cleanup TSA pipeline template parameter
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: feature-request

#493 Update packages
  README.md
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#496 Add logging to make it easier to find settings issues
  bundled/tool/lsp_server.py
  src/common/settings.ts
Labels: debt
