Repository microsoft/vscode-black-formatter, pull requests merged in 2024-02, with the labels that each got.

#433 Add environment and vars for updater workflow
  .github/workflows/update-packages.yml
  .github/workflows/update-version.yml
  .github/workflows/update_version.py
Labels: no-changelog

#439 Remove workflows
  .github/workflows/update-packages.yml
  .github/workflows/update-version.yml
  .github/workflows/update_packages.py
  .github/workflows/update_version.py
Labels: no-changelog

#441 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#442 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#431 Add smoke test to detect extension load and python selection
  .github/workflows/pr-check.yml
  .vscode/launch.json
  bundled/tool/lsp_server.py
  package.json
  src/common/python.ts
  src/test/ts_tests/index.ts
  src/test/ts_tests/runSmokeTest.ts
  src/test/ts_tests/test_data/project/.vscode/settings.json
  src/test/ts_tests/test_data/project/myscript.formatted
  src/test/ts_tests/test_data/project/myscript.py
  src/test/ts_tests/test_data/project/myscript.unformatted
  src/test/ts_tests/tests/common/minimal.smoke.test.ts
Labels: debt

#445 Update min vscode version
  package.json
Labels: bug

#462 Update extension version to recovery release
  package-lock.json
  package.json
Labels: no-changelog

#460 Update `black` with bug fix for skipping formatting files that are symlinked
  README.md
  requirements.txt
Labels: bug

#461 Add a setting to allow server transport selection
  README.md
  package.json
  package.nls.json
  src/common/server.ts
  src/common/settings.ts
Labels: bug

#465 Update `black` with bug fix for skipping formatting files that are symlinked
  README.md
  requirements.txt
Labels: bug
